### PR TITLE
Add support for OCaml 4.14

### PR DESCRIPTION
**Pull request by kit-ty-kate**

### CODE REVIEW

**Comment by OlivierNicole** [comment]
I also think this would be useful—in fact, I performed exactly the same changes to get notty to compile on trunk OCaml, as I had not noticed this PR.

**Comment by kit-ty-kate** [comment]
@pqwy the full release of 4.14 is approaching quickly. If you don’t have time to deal with this right now or anymore, you might want to add commit rights to someone or transfer ownership to https://github.com/ocaml-community/ for example

**Comment by smuenzel** [comment]
ping @pqwy, can this be merged?

**Comment by pqwy** [comment]
These are now included in the rewritten history up to 389366c023396017aa21efcdbb07ade5ba0974c5.

Thanks for the fixes — and for the warm encouragements to apply them!

**Comment by pqwy** [comment]
Part of [v0.2.3](https://github.com/pqwy/notty/releases/tag/v0.2.3).

**Pull request closed without merging**
